import NavigateLink from '@/components/NavigateLink'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Providers from './providers'

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
})

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en' suppressHydrationWarning >
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <nav className='flex gap-4 list-none px-20 py-5'>
               <li>
                  <NavigateLink
                     className='text-gray-500 text-2xl font-bold'
                     active='text-blue-900'
                     href='/'
                  >
                     Home
                  </NavigateLink>
               </li>
               <li>
                  <NavigateLink
                     className='text-gray-500 text-2xl font-bold'
                     href='/about'
                     active='text-blue-900'
                  >
                     About
                  </NavigateLink>
               </li>
               <li>
                  <NavigateLink
                     className='text-gray-500 text-2xl font-bold'
                     active='text-blue-900'
                     href='/auth'
                  >
                     Auth
                  </NavigateLink>
               </li>
            </nav>
            <Providers>{children}</Providers>
         </body>
      </html>
   )
}
